# Generated by Django 4.2.6 on 2023-10-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
