# Generated by Django 4.2.6 on 2023-10-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0007_alter_post_shared_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
