# Generated by Django 4.2.6 on 2023-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0008_alter_post_shared_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
