# Generated by Django 4.2.6 on 2023-10-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostApp', '0014_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=100),
        ),
    ]
